### PR TITLE
Test using the official AWS test suite and multiple fixes to make them pass

### PR DESCRIPTION
**Pull request by yrodiere**
Hello,

As part of my work on Hibernate Search (https://github.com/hibernate/hibernate-search/pull/1454), I used this project to handle AWS authentication. I noticed that not every normalization required by AWS is implemented, so here is a PR to address that.

The first commit just changes the .gitignore file.

The second commit adds the official test suite from AWS to the project: http://docs.aws.amazon.com/general/latest/gr/signature-v4-test-suite.html

The third commit relaxes the constraints over how the path and query are passed to the signer. It is needed in order to use the AWS test suite, and I also happen to need it in Hibernate Search.

The following commits fix the issues that prevented the test suite to pass.

@lucasweb78 Do you think this could get merged, and hopefully released anytime soon?

### CODE REVIEW

**Comment by lucasweb78** [comment]
Thanks for the contributions. I'll review and merge later today push to maven central over the weekend.

**Comment by lucasweb78** [comment]
This is now merged and I have pushed it to Maven Central as version 1.3. It should hopefully be available there in the next few hours

**Comment by yrodiere** [comment]
@lucasweb78 It's available and works just fine. Thanks a lot!

**Comment by Sanne** [comment]
Awesome! Thanks @lucasweb78

**Pull request merged**
